### ISSUE TITLE
[Client] 랜딩페이지 프로토타입

### ISSUE THREAD

**Issue by zuzokim** [codestates/re-collect-client#13]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: `actions from client`

### TODO
1. [x] 랜딩페이지 laptop 기준 기본CSS 구현
2. [x] 랜딩페이지 tablet, mobile 반응형CSS 구현 
3. [x] react-reveal 라이브러리 활용, 스크롤 애니메이션 구현
4. [x] 로고, 세부이미지 png 제작, 파비콘 설정

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `High`
