### ISSUE TITLE
[Client] Pop-up 모달창 만들기

### ISSUE THREAD

**Issue by siyooonkim** [codestates/re-collect-client#19]
### ISSUE
- Group:  client
- Type: feature
- Detail: Login, Sign-Up, ForgotPWD, Explore 등 각 페이지에 필요한 Pop-Up 모달 만들 예정

### TODO
1. [x] 구글링 및 이전 프로젝트 PopUp 참고하며 공부하기
2. [x] 각 페이지 별 Pop-up 모달 만들기
3. [x] 모달 창 반응형 대응

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint 1
- Urgency: High,
