### ISSUE TITLE
[Client] Nav, Footer 컴포넌트 제작 및 반응형 적용

### ISSUE THREAD

**Issue by zuzokim** [codestates/re-collect-client#25]
### ISSUE
- Group:  client
- Type: feature
- Detail: actions from client redux

### TODO
1. [x] Nav, Footer 컴포넌트 제작 및 반응형 적용 (햄버거 토글, 정렬)
2. [x] react-router link 각 페이지로 라우팅
3. [x] Footer 팀원 깃헙 링크, 피드백 메일 전송 링크, 외부(sns) 공유 링크 첨부, 여유되면 total visit 구현 시도해보기

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint1
- Urgency: High
