### ISSUE TITLE
[Client] 리콜렉트 컴포넌트, 북마크 추가 토스트

### ISSUE THREAD

**Issue by MartinLeeSJ** [codestates/re-collect-client#28]
### ISSUE
- Group:  client
- Type: feature,
- Detail: recollect component완성

### TODO
1. [x] recollect component 완성, 반응형 적용
2. [ ] bookmark 추가 토스트 (북마크가 추가되었습니다.)
3. [x] 시간이 된다면 콜렉트 페이지 테블릿 모드일때 북마크 그리드 다시 고쳐보기

### Estimated time
Pick one
### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint 1
- Urgency: High
