### ISSUE TITLE
[Client] Navigation컴포넌트-Explore,Modal컴포넌트 연결

### ISSUE THREAD

**Issue by siyooonkim** [codestates/re-collect-client#29]
### ISSUE
- Group:  client
- Type: feature
- Detail: Navigation컴포넌트-Explore, Modal컴포넌트 연결

### TODO
1. [ ] Navaigation 컴포넌트의 Explore, Login 버튼 클릭시 각 컴포넌트 호출
2. [ ] Explore 컴포넌트 리팩토링
3. [ ] Modal 컴포넌트 리팩토링 

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint 1
- Urgency: High
