### ISSUE TITLE
[Client] Profile 페이지 회원정보수정,회원탈퇴 구현

### ISSUE THREAD

**Issue by zuzokim** [codestates/re-collect-client#43]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: `actions from client` `redux`

### TODO
1. [x] Profile 페이지 비밀번호변경,회원탈퇴 모달 제작 후 로직 구현(redux)
2. [x] Profile 페이지 유저네임변경 로직 구현(redux)
3. [x] company,gitRepo 추가/수정 로직 구현 (input태그 활성/비활성 분기로직포함)
4. [ ] favorite 북마크 get 요청/filtering 로직 구현(redux)
5. [x] Nav바 isLogin여부에 따른 렌더링(login/logout/profile) 라우팅 수정

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
