### ISSUE TITLE
[Client] 북마크 작성 액션,리듀서 작성

### ISSUE THREAD

**Issue by CodingGorani** [codestates/re-collect-client#47]
### ISSUE
- Group:  client
- Type:  feature
- Detail: 북마크 작성 리듀서 ,액션

### TODO
1. [ ]  리액트 셀렉트 모듈 공부 - 카테고리를 선택했을 때 그 정보를 상태에 업데이트 하는 방법
2. [ ] 인풋태그 입력시 상태에 업데이트 방법
3. [ ] 인풋태그 글자 수 제한
4. [ ] 작성시 동작하는 thunk 작성

### Estimated time
Pick one

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint 2
- Urgency: High
